4
Vinogradov-Mikhail/semestr3 pull request #3
Opened 2016-12-19 23:13 UTC by Vinogradov-Mikhail

2016-12-20 07:21 UTC, yurii-litvinov requested changes
- Желательно делать недоступными кнопки "отменить"/"повторить", если undo (redo) стек пуст.
- что-то кнопка "Переместить" никакого видимого эффекта не производит, кроме того, что становится нельзя рисовать линию.

2016-12-20 07:21 UTC, yurii-litvinov commented on GraphiEditor/GraphiEditor/Editor.cs
> +        private void pictureBoxPaintHandler(object sender, PaintEventArgs e)
Методы пишутся с заглавной в дотнете

2016-12-20 16:40 UTC, Vinogradov-Mikhail commented
переместить - она перемещает конец линии

2016-12-21 23:05 UTC, yurii-litvinov requested changes
Не компилится

2016-12-21 23:05 UTC, yurii-litvinov commented on GraphiEditor/GraphiEditor/Editor.cs
> +        }
Этот метод можно было записать в две строчки :)

2016-12-21 23:15 UTC, Vinogradov-Mikhail commented
?

2016-12-21 23:26 UTC, Vinogradov-Mikhail commented
проблема было в том что методы я сделал с заглавной а ссылки остались на методы с маленькой

2016-12-22 11:22 UTC, yurii-litvinov commented
Ну да, но кнопка "Переместить" у меня всё-таки ничего не перемещает, на конец линии кликал, пытался перетаскивать, просто кликать на сцену --- не помогло :) Ну и надо доисправлять замечания.

2016-12-22 14:13 UTC, Vinogradov-Mikhail commented
Странно. Я запустил. Все работает. Я нарисовал линию, затем нажал на кнопку переместить, кликнул на конец линии и у меня линия перемещается вместе с курсором.

2016-12-22 15:53 UTC, yurii-litvinov approved these changes

2016-12-22 16:51 UTC, merged